---

- name : deploy hardening-rules on Ubuntu hosts
  hosts: ubuntu
  become: true
  gather_facts: true

  tasks:
    - name : update system
      ansible.builtin.include_role:
        name: update-system

    - name : deploy ssh hardening rules
      ansible.builtin.include_role:
        name: ssh-hardening
      
    - name : deploy permissions hardening rules
      ansible.builtin.include_role:
        name: perm-hardening
    
    - name : deploy disable ipv6 rules
      ansible.builtin.include_role:
        name: disable_ipv6
    
    - name : remove useless services
      ansible.builtin.include_role:
        name: useless_services